# Dispatch with Energy Storage

In [1]:
import ams

import datetime

import numpy as np

import cvxpy as cp

In [2]:
print("Last run time:", datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S"))

print(f'ams:{ams.__version__}')

Last run time: 2023-11-10 00:12:54
ams:0.7.3.post42.dev0+gd7a5b95


In [3]:
ams.config_logger(stream_level=10)

In [4]:
sp = ams.load(ams.get_case('ieee39/ieee39_uced_esd1_t2.xlsx'),
              setup=True,)

Input format guessed as xlsx.
Parsing input file "/Users/jinningwang/Documents/work/ams/ams/cases/ieee39/ieee39_uced_esd1_t2.xlsx"...
Input file parsed in 0.1132 seconds.
System set up in 0.0038 seconds.


In [5]:
sp.RTED2.init()

RTED2 data check passed.
- Generating symbols for RTED2
Set constrs pb: sum(pl) - sum(pg) == 0
Set constrs pinj: CftT@plf - pl - pn == 0
Set constrs lub: PTDF @ (pn - pl) - rate_a <= 0
Set constrs llb: - PTDF @ (pn - pl) - rate_a <= 0
Set constrs rbu: gs @ mul(ug, pru) - dud == 0
Set constrs rbd: gs @ mul(ug, prd) - ddd == 0
Set constrs rru: mul(ug, pg + pru) - pmax <= 0
Set constrs rrd: mul(ug, -pg + prd) - pmin <= 0
Set constrs rgu: mul(ug, pg-pg0-R10) <= 0
Set constrs rgd: mul(ug, -pg+pg0-R10) <= 0
Set constrs ceb: uce + ude - 1 == 0
Set constrs cpe: ce @ pg - zce - zde == 0
Set constrs zce1: -zce + pce <= 0
Set constrs zce2: zce - pce - Mb dot (1-uce) <= 0
Set constrs zce3: zce - Mb dot uce <= 0
Set constrs zde1: -zde + pde <= 0
Set constrs zde2: zde - pde - Mb dot (1-ude) <= 0
Set constrs zde3: zde - Mb dot ude <= 0
Set constrs SOCb: mul(En, (SOC - SOCinit)) - t dot mul(EtaC, zce)+ t dot mul(REtaD, zde) == 0
Set obj tc: min. sum(c2 @ (t dot pg)**2) + sum(c1 @ (t dot pg)) + ug * c0

True

In [6]:
sp.RTED2.run(solver='GUROBI')

RTED2 has already been initialized.


Set parameter Username
Academic license - for non-commercial use only - expires 2024-05-21


RTED2 solved as optimal in 0.0793 seconds, converged after 33 iterations using solver GUROBI.


True

In [7]:
print(f"pg={sp.RTED2.pg.v}")

print(f"uce={sp.RTED2.uce.v}")
print(f"pce={sp.RTED2.pce.v}")
print(f"zce={sp.RTED2.zce.v}")

print(f"ude={sp.RTED2.ude.v}")
print(f"pde={sp.RTED2.pde.v}")
print(f"zde={sp.RTED2.zde.v}")

print(f"SOC={sp.RTED2.SOC.v}")
print(f"obj={sp.RTED2.obj.v}")

pg=[6.01822025 5.99427957 5.97043409 5.08       5.98234496 5.8
 5.64       6.00623798 6.03022646 6.04225669]
uce=[0. 0.]
pce=[0. 0.]
zce=[0. 0.]
ude=[1. 1.]
pde=[3.00911012 3.00911012]
zde=[3.00911012 3.00911012]
SOC=[0.49749241 0.49749241]
obj=592.8203580808986


In [8]:
sp.RTED2.set(src='c1', attr='v', idx='GCost_1', value=999)
sp.RTED2.run(force_init=True, solver='GUROBI')

RTED2 data check passed.
Set constrs pb: sum(pl) - sum(pg) == 0
Set constrs pinj: CftT@plf - pl - pn == 0
Set constrs lub: PTDF @ (pn - pl) - rate_a <= 0
Set constrs llb: - PTDF @ (pn - pl) - rate_a <= 0
Set constrs rbu: gs @ mul(ug, pru) - dud == 0
Set constrs rbd: gs @ mul(ug, prd) - ddd == 0
Set constrs rru: mul(ug, pg + pru) - pmax <= 0
Set constrs rrd: mul(ug, -pg + prd) - pmin <= 0
Set constrs rgu: mul(ug, pg-pg0-R10) <= 0
Set constrs rgd: mul(ug, -pg+pg0-R10) <= 0
Set constrs ceb: uce + ude - 1 == 0
Set constrs cpe: ce @ pg - zce - zde == 0
Set constrs zce1: -zce + pce <= 0
Set constrs zce2: zce - pce - Mb dot (1-uce) <= 0
Set constrs zce3: zce - Mb dot uce <= 0
Set constrs zde1: -zde + pde <= 0
Set constrs zde2: zde - pde - Mb dot (1-ude) <= 0
Set constrs zde3: zde - Mb dot ude <= 0
Set constrs SOCb: mul(En, (SOC - SOCinit)) - t dot mul(EtaC, zce)+ t dot mul(REtaD, zde) == 0
Set obj tc: min. sum(c2 @ (t dot pg)**2) + sum(c1 @ (t dot pg)) + ug * c0 + sum(cru * pru + crd * prd)
R

True

In [9]:
print(f"pg={sp.RTED2.pg.v}")

print(f"uce={sp.RTED2.uce.v}")
print(f"pce={sp.RTED2.pce.v}")
print(f"zce={sp.RTED2.zce.v}")

print(f"ude={sp.RTED2.ude.v}")
print(f"pde={sp.RTED2.pde.v}")
print(f"zde={sp.RTED2.zde.v}")

print(f"SOC={sp.RTED2.SOC.v}")
print(f"obj={sp.RTED2.obj.v}")

pg=[0.         7.13724518 6.52       5.08       6.87       5.8
 5.64       7.15034313 7.17661754 7.18979416]
uce=[0. 0.]
pce=[0. 0.]
zce=[0. 0.]
ude=[1. 1.]
pde=[0. 0.]
zde=[0. 0.]
SOC=[0.5 0.5]
obj=622.4342380817811


In [10]:
sp = ams.load(ams.get_case('ieee39/ieee39_uced_esd1_t2.xlsx'),
              setup=True,)

Input format guessed as xlsx.
Parsing input file "/Users/jinningwang/Documents/work/ams/ams/cases/ieee39/ieee39_uced_esd1_t2.xlsx"...
Input file parsed in 0.0892 seconds.
System set up in 0.0100 seconds.


In [11]:
sp.ED2.REtaD

NumOp: ED2.REtaD, v in shape of (2,)

In [12]:
sp.ED2.init(no_code=False)

ED2 data check passed.
- Generating symbols for ED2
Set constrs pb: - gs @ pg + pds == 0
Code Constr: om.constrs["pb"]=- self.om.rtn.gs.v @ self.om.pg + self.om.rtn.pds.v == 0
Set constrs pinj: Cg @ (pn - Rpd) - pg == 0
Code Constr: om.constrs["pinj"]=self.om.rtn.Cg.v @ (self.om.pn - self.om.rtn.Rpd.v) - self.om.pg == 0
Set constrs lub: PTDF @ (pn - Rpd) - RRA <= 0
Code Constr: om.constrs["lub"]=self.om.rtn.PTDF.v @ (self.om.pn - self.om.rtn.Rpd.v) - self.om.rtn.RRA.v <= 0
Set constrs llb: -PTDF @ (pn - Rpd) - RRA <= 0
Code Constr: om.constrs["llb"]=-self.om.rtn.PTDF.v @ (self.om.pn - self.om.rtn.Rpd.v) - self.om.rtn.RRA.v <= 0
Set constrs sr: -gs@multiply(Rpmax - pg, Rug) + dsr <= 0
Code Constr: om.constrs["sr"]=-self.om.rtn.gs.v@cp.multiply(self.om.rtn.Rpmax.v - self.om.pg, self.om.rtn.Rug.v) + self.om.rtn.dsr.v <= 0
Set constrs rgu: pg @ Mr - t dot RR30 <= 0
Code Constr: om.constrs["rgu"]=self.om.pg @ self.om.rtn.Mr.v - self.rtn.config.t * self.om.rtn.RR30.v <= 0
Set constrs rgd: -p

True

In [13]:
sp.ED2.run(solver="GUROBI")

ED2 has already been initialized.
ED2 solved as optimal in 0.0905 seconds, converged after 68 iterations using solver GUROBI.


True

In [14]:
print(f"pg={sp.ED2.pg.v[0, :]}")

nr = 3

print(f"uce={sp.ED2.uce.v}")
print(f"pce={sp.ED2.pce.v.round(nr)}")
print(f"zce={sp.ED2.zce.v.round(nr)}")

print(f"ude={sp.ED2.ude.v}")
print(f"pde={sp.ED2.pde.v.round(nr)}")
print(f"zde={sp.ED2.zde.v.round(nr)}")

print(f"SOC={sp.ED2.SOC.v.round(nr)}")
print(f"obj={sp.ED2.obj.v}")

pg=[3.76453119 3.72343444 3.65885384]
uce=[[0. 0. 1.]
 [0. 0. 1.]]
pce=[[0.    0.    1.829]
 [0.    0.    1.829]]
zce=[[0.    0.    1.829]
 [0.    0.    1.829]]
ude=[[1. 1. 0.]
 [1. 1. 0.]]
pde=[[1.882 1.862 0.   ]
 [1.882 1.862 0.   ]]
zde=[[1.882 1.862 0.   ]
 [1.882 1.862 0.   ]]
SOC=[[0.481 0.1   0.5  ]
 [0.481 0.1   0.5  ]]
obj=45508.58507547713


In [15]:
sp.ED2.SOCb.e_str

'mul(EnR, SOC @ Mre) - t dot mul(EtaCR, zce[:, 1:]) + t dot mul(REtaDR, zde[:, 1:])'

In [16]:
np.multiply(sp.ED2.EnR.v, np.matmul(sp.ED2.SOC.v, sp.ED2.Mre.v))

array([[-38.11773441,  40.        ],
       [-38.11773441,  40.        ]])

In [17]:
-sp.ED2.config.t * np.multiply(sp.ED2.EtaCR.v, sp.ED2.zce.v[:, 1:])

array([[-0.        , -1.82942692],
       [-0.        , -1.82942692]])

In [18]:
sp.ED2.config.t * np.multiply(sp.ED2.REtaDR.v, sp.ED2.zde.v[:, 1:])

array([[1.86171722, 0.        ],
       [1.86171722, 0.        ]])

In [19]:
sp.ED2.SOCb0.e_str

'mul(En, SOC[:, 0] - SOCinit) - t dot mul(EtaC, zce[:, 0]) + t dot mul(REtaD, zde[:, 0])'

In [22]:
np.multiply(sp.ED2.En.v, sp.ED2.SOC.v[:, 0]-sp.ED2.SOCinit.v)

array([-1.88226559, -1.88226559])

In [25]:
-sp.ED2.config.t * np.multiply(sp.ED2.EtaC.v, sp.ED2.zce.v[:, 0])

array([-0., -0.])

In [26]:
sp.ED2.config.t * np.multiply(sp.ED2.REtaD.v, sp.ED2.zde.v[:, 0])

array([1.88226559, 1.88226559])