# PFlow

In [1]:
import numpy as np

import andes
import ams

import cvxpy as cp

from ams.solver.pypower.runpf import runpf, rundcpf

In [2]:
ams.__version__

'0.6.4.post10.dev0+g94979d4'

In [3]:
andes.config_logger(stream_level=10)

In [4]:
sa = andes.load(andes.get_case('ieee14/ieee14_ace.xlsx'),
              setup=True,)

Working directory: "/Users/jinningwang/Documents/work/ams/dev/demo"
Found files: ['/Users/jinningwang/Documents/work/mambaforge/envs/ams/lib/python3.9/site-packages/andes/cases/ieee14/ieee14_ace.xlsx']
> Loaded config from file "/Users/jinningwang/.andes/andes.rc"
> Loaded generated Python code in "/Users/jinningwang/.andes/pycode".
Input format guessed as xlsx.
Parsing input file "/Users/jinningwang/Documents/work/mambaforge/envs/ams/lib/python3.9/site-packages/andes/cases/ieee14/ieee14_ace.xlsx"...
Input file parsed in 0.3893 seconds.
Setting internal address for Bus
Setting internal address for PQ
Setting internal address for PV
Setting internal address for Slack
Setting internal address for Shunt
Setting internal address for Line
Setting internal address for Area
System internal structure set up in 0.0249 seconds.


In [5]:
ams.config_logger(stream_level=10)

In [6]:
case1 = ams.get_case('matpower/case14.m')
case2 = ams.get_case('ieee14/ieee14.xlsx')
case3 = ams.get_case('matpower/case_ACTIVSg2000.m')
case4 = ams.get_case('pypower/case14.py')
sp = ams.load(case4, setup=True,)

Working directory: "/Users/jinningwang/Documents/work/ams/dev/demo"
Found files: ['/Users/jinningwang/Documents/work/ams/ams/cases/pypower/case14.py']
Input format guessed as pypower.
Parsing input file "/Users/jinningwang/Documents/work/ams/ams/cases/pypower/case14.py"...
Input file parsed in 0.0228 seconds.
Adjusting the bus index to start from 0.
System set up in 0.0060 seconds.


In [7]:
sp.PFlow.run()

Setup model for PFlow
- Generating symbols for PFlow
Set constrs power balance: self.constrs["pb"]=cp.sum(self.routine.pd.v) - cp.sum(self.pg) == 0
PFlow has no objective function.
PFlow model set up in 0.0055 seconds.
Adjusting the bus index to start from 0.
PYPOWER Version 5.1.4, 27-June-2018
 -- DC Power Flow

PFlow completed in 0.0052 seconds with exit code 0.


0

In [8]:
sp.PFlow.pg.v

array([2.19, 0.4 , 0.  , 0.  , 0.  ])

In [9]:
sp.PFlow.qg.v

array([-0.169,  0.424,  0.234,  0.122,  0.174])

In [10]:
sp.PFlow.aBus.v

array([ 0.        , -0.0874761 , -0.22608407, -0.18471984, -0.1587184 ,
       -0.25921768, -0.24272389, -0.24272389, -0.273924  , -0.27880104,
       -0.27260036, -0.27867806, -0.28169097, -0.29999221])

In [11]:
sp.PFlow.vBus.v

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [12]:
sp.DCPF.run()

Setup model for DCPF
- Generating symbols for DCPF
Set constrs power balance: self.constrs["pb"]=cp.sum(self.routine.pd.v) - cp.sum(self.pg) == 0
DCPF has no objective function.
DCPF model set up in 0.0017 seconds.
Adjusting the bus index to start from 0.
PYPOWER Version 5.1.4, 27-June-2018
 -- DC Power Flow

DCPF completed in 0.0035 seconds with exit code 0.


0

In [13]:
sp.DCPF.pg.v

array([2.19, 0.4 , 0.  , 0.  , 0.  ])