# PFlow

In [1]:
import numpy as np

import andes
import ams

import cvxpy as cp

from ams.solver.pypower.runpf import runpf, rundcpf

In [2]:
ams.__version__

'0.6.5.post20.dev0+g19099c9'

In [3]:
ams.config_logger(stream_level=10)

In [4]:
case1 = ams.get_case('matpower/case14.m')
case2 = ams.get_case('ieee14/ieee14_opf.xlsx')
case3 = ams.get_case('matpower/case_ACTIVSg2000.m')
case4 = ams.get_case('pypower/case14.py')

sp = ams.load(case4, setup=True,)

Input format guessed as pypower.
Parsing input file "/Users/jinningwang/Documents/work/ams/ams/cases/pypower/case14.py"...
Input file parsed in 0.0040 seconds.
Adjust bus index to start from 0.
System set up in 0.0034 seconds.


In [5]:
sp.ACOPF.run()

Setup model for ACOPF
ACOPF data check passed.
- Generating symbols for ACOPF
Set constrs pb: self.constrs["pb"]=cp.sum( self.routine.pd1.v ) +cp.sum( self.routine.pd2.v ) - cp.sum( self.pg ) == 0
ACOPF model set up in 0.0023 seconds.
Adjust bus index to start from 0.
PYPOWER Version 5.1.4, 27-June-2018
 -- AC Optimal Power Flow



Python Interior Point Solver - PIPS, Version 1.0, 07-Feb-2011


ACOPF completed in 0.2661 seconds with exit code 0.


Converged!


0

In [6]:
sp.DCPF.run()

Setup model for DCPF
DCPF data check passed.
- Generating symbols for DCPF
DCPF has no objective function.
DCPF model set up in 0.0013 seconds.
Adjust bus index to start from 0.
PYPOWER Version 5.1.4, 27-June-2018
 -- DC Power Flow

DCPF completed in 0.0039 seconds with exit code 0.


0

In [7]:
sp.PFlow.run()

Setup model for PFlow
PFlow data check passed.
- Generating symbols for PFlow
Set constrs pb: self.constrs["pb"]=cp.sum(self.routine.pd.v) - cp.sum(self.pg) == 0
PFlow has no objective function.
PFlow model set up in 0.0025 seconds.
Adjust bus index to start from 0.
PYPOWER Version 5.1.4, 27-June-2018

Newton's method power flow converged in 2 iterations.

PFlow completed in 0.0111 seconds with exit code 0.


 -- AC Power Flow (Newton)



0

In [8]:
sp.PFlow.pg.v

array([2.32393272, 0.4       , 0.        , 0.        , 0.        ])

In [9]:
sp.PFlow.qg.v

array([-0.16549301,  0.435571  ,  0.25075348,  0.12730944,  0.17623451])

In [10]:
sp.PFlow.aBus.v

array([ 0.        , -0.08696259, -0.22209489, -0.17999408, -0.15313264,
       -0.24820234, -0.23316948, -0.23316948, -0.26072638, -0.26349739,
       -0.25814505, -0.26311859, -0.26452692, -0.27983989])

In [11]:
sp.PFlow.vBus.v

array([1.06      , 1.045     , 1.01      , 1.01767085, 1.01951386,
       1.07      , 1.06151953, 1.09      , 1.05593172, 1.05098463,
       1.05690652, 1.05518856, 1.05038171, 1.03552995])

In [12]:
sp.DCPF.run()

Adjust bus index to start from 0.
PYPOWER Version 5.1.4, 27-June-2018
 -- DC Power Flow

DCPF completed in 0.0049 seconds with exit code 0.


0

In [13]:
sp.DCPF.pg.v

array([2.19, 0.4 , 0.  , 0.  , 0.  ])