# Type

In [1]:
import numpy as np

import andes
import ams

import cvxpy as cp

In [2]:
ams.__version__

'0.6.4.post20.dev0+g596bf15'

In [3]:
andes.config_logger(stream_level=10)

In [4]:
sa = andes.load(andes.get_case('ieee14/ieee14_ace.xlsx'),
              setup=True,)

Working directory: "/home/jwang/work/ams/dev/demo"
Found files: ['/home/jwang/.local/lib/python3.10/site-packages/andes/cases/ieee14/ieee14_ace.xlsx']
> Loaded config from file "/home/jwang/.andes/andes.rc"
> Loaded generated Python code in "/home/jwang/.andes/pycode".
Input format guessed as xlsx.
Parsing input file "/home/jwang/.local/lib/python3.10/site-packages/andes/cases/ieee14/ieee14_ace.xlsx"...
Input file parsed in 0.5233 seconds.
Setting internal address for Bus
Setting internal address for PQ
Setting internal address for PV
Setting internal address for Slack
Setting internal address for Shunt
Setting internal address for Line
Setting internal address for Area
System internal structure set up in 0.0611 seconds.


In [5]:
ams.config_logger(stream_level=10)

In [6]:
case1 = ams.get_case('matpower/case14.m')
case2 = ams.get_case('ieee14/ieee14.xlsx')
case3 = ams.get_case('matpower/case_ACTIVSg2000.m')
sp = ams.load(case1, setup=True,)

ppc = ams.io.pypower.system2ppc(sp)

Working directory: "/home/jwang/work/ams/dev/demo"
Found files: ['/home/jwang/work/ams/ams/cases/matpower/case14.m']
Input format guessed as matpower.
Parsing input file "/home/jwang/work/ams/ams/cases/matpower/case14.m"...
Detected raw file encoding: {'encoding': 'ascii', 'confidence': 1.0, 'language': ''}
CASE14    Power flow data for IEEE 14 bus test case.
Input file parsed in 0.0134 seconds.
Line rate_a is corrected to large value automatically.
Adjusting the bus index to start from 0.
System set up in 0.0133 seconds.
Adjusting the bus index to start from 0.


In [7]:
sp.models

OrderedDict([('Summary', Summary (0 devices) at 0x7faf1e3ac370),
             ('Bus', Bus (14 devices) at 0x7faf2aee12d0),
             ('PQ', PQ (11 devices) at 0x7faf1e3acd90),
             ('PV', PV (4 devices) at 0x7faf1e3ad420),
             ('Slack', Slack (1 device) at 0x7faf1e3adff0),
             ('Shunt', Shunt (1 device) at 0x7faf1e3aea70),
             ('Line', Line (20 devices) at 0x7faf1e3aeef0),
             ('Area', Area (0 devices) at 0x7faf1e3afaf0),
             ('GCost', GCost (5 devices) at 0x7faf1e3afee0)])

In [8]:
sp.groups

OrderedDict([('ACLine', ACLine (20 devices) at 0x7faf1e3ac190),
             ('ACTopology', ACTopology (14 devices) at 0x7faf1e3ac1c0),
             ('Collection', Collection (0 devices) at 0x7faf1e3ac1f0),
             ('Cost', Cost (5 devices) at 0x7faf1e3ac220),
             ('Information', Information (0 devices) at 0x7faf1e3ac250),
             ('StaticGen', StaticGen (5 devices) at 0x7faf1e3ac280),
             ('StaticLoad', StaticLoad (11 devices) at 0x7faf1e3ac2b0),
             ('StaticShunt', StaticShunt (1 device) at 0x7faf1e3ac2e0),
             ('Undefined', Undefined (0 devices) at 0x7faf1e3ac310)])

In [9]:
sp.routines

OrderedDict([('DCPF', DC Power Flow),
             ('PFlow', AC Power Flow),
             ('DCOPF', DC Optimal Power Flow),
             ('ACOPF', AC Optimal Power Flow)])

In [10]:
sp.types

OrderedDict([('AC', AC (0 routines) at 0x7faf1e42feb0),
             ('DC', DC (0 routines) at 0x7faf1e42ff70),
             ('ED', ED (0 routines) at 0x7faf1e42ffd0),
             ('PF', PF (0 routines) at 0x7faf1e3ac070),
             ('UC', UC (0 routines) at 0x7faf1e3ac0d0),
             ('Undefined', Undefined (0 routines) at 0x7faf1e3ac130)])

In [11]:
sp.AC

AC (0 routines) at 0x7faf1e42feb0

In [12]:
sp.DC

DC (0 routines) at 0x7faf1e42ff70

In [13]:
sp.PF

PF (0 routines) at 0x7faf1e3ac070

In [14]:
sp.DCPF.run()

Setup model for DCPF
- Generating symbols for DCPF
Set constrs power balance: self.constrs["pb"]=cp.sum(self.routine.pd.v) - cp.sum(self.pg) == 0
DCPF has no objective function.
DCPF model set up in 0.0064 seconds.
Adjusting the bus index to start from 0.
PYPOWER Version 5.1.4, 27-June-2018
 -- DC Power Flow

DCPF completed in 0.0117 seconds with exit code 0.


0

In [15]:
sp.PFlow.run()

Setup model for PFlow
- Generating symbols for PFlow
Set constrs power balance: self.constrs["pb"]=cp.sum(self.routine.pd.v) - cp.sum(self.pg) == 0
PFlow has no objective function.
PFlow model set up in 0.0066 seconds.
Adjusting the bus index to start from 0.
PYPOWER Version 5.1.4, 27-June-2018
 -- DC Power Flow

PFlow completed in 0.0118 seconds with exit code 0.


0

In [16]:
sp.DCOPF.run(solver='GUROBI')

Setup model of DCOPF
- Generating symbols for DCOPF
Set constrs power balance: self.constrs["pb"]=cp.sum(self.routine.pd.v) - cp.sum(self.pg) == 0
Set constrs line limits upper bound: self.constrs["lub"]=self.routine.PTDF1.v @ (self.pg - self.routine.pd1.v) - self.routine.PTDF2.v @ self.routine.pd2.v - self.routine.rate_a.v <= 0
Set constrs line limits lower bound: self.constrs["llb"]=- self.routine.PTDF1.v @ (self.pg - self.routine.pd1.v) + self.routine.PTDF2.v @ self.routine.pd2.v - self.routine.rate_a.v <= 0
DCOPF model set up in 0.0085 seconds.


Restricted license - for non-production use only - expires 2024-10-28


DCOPF completed in 0.0238 seconds with exit code 0.


In [17]:
sp.DCOPF.obj

tc: sum(c2 * pg**2 + c1 * pg + c0), tc=7642.5918

In [18]:
sp.DCOPF.pg.v

array([2.20967695, 0.38032305, 0.        , 0.        , 0.        ])

In [19]:
sp.ACOPF.run()

Setup model for ACOPF
- Generating symbols for ACOPF
Set constrs power balance: self.constrs["pb"]=cp.sum(self.routine.pd.v) - cp.sum(self.pg) == 0
ACOPF model set up in 0.0051 seconds.
Adjusting the bus index to start from 0.
PYPOWER Version 5.1.4, 27-June-2018
 -- AC Optimal Power Flow



Python Interior Point Solver - PIPS, Version 1.0, 07-Feb-2011


ACOPF completed in 0.5647 seconds with exit code 0.


Converged!


0

In [20]:
sp.ACOPF.obj

tc: sum(c2 * pg**2 + c1 * pg + c0), tc=8186.8829

In [21]:
sp.ACOPF.pg.v

array([1.52170203, 0.40208407, 0.52814901, 0.0003197 , 0.19826406])

In [22]:
sp.ACOPF.qg.v

array([0.05073508, 0.13834569, 0.19927507, 0.09809777, 0.07063822])

In [23]:
sp.ACOPF.aBus.v

array([ 0.        , -0.05270412, -0.12676006, -0.12193981, -0.10546813,
       -0.19070688, -0.15258788, -0.1211677 , -0.18850874, -0.1939532 ,
       -0.19456553, -0.20486421, -0.20523061, -0.2135537 ])

In [24]:
sp.ACOPF.vBus.v

array([1.05999989, 1.04227009, 1.0228202 , 1.0188708 , 1.01989242,
       1.05999979, 1.04877868, 1.05999964, 1.0467066 , 1.04171286,
       1.04741529, 1.04497152, 1.04047321, 1.02585715])