# OPF

In [1]:
import numpy as np

import andes
import ams

import cvxpy as cp

In [2]:
ams.__version__

'0.6.4.post38.dev0+gaa8bfca'

In [3]:
andes.config_logger(stream_level=10)

In [4]:
sa = andes.load(andes.get_case('ieee14/ieee14_ace.xlsx'),
              setup=True,)

Working directory: "/Users/jinningwang/Documents/work/ams/dev/demo"
Found files: ['/Users/jinningwang/Documents/work/mambaforge/envs/ams/lib/python3.9/site-packages/andes/cases/ieee14/ieee14_ace.xlsx']
> Loaded config from file "/Users/jinningwang/.andes/andes.rc"
> Loaded generated Python code in "/Users/jinningwang/.andes/pycode".
Input format guessed as xlsx.
Parsing input file "/Users/jinningwang/Documents/work/mambaforge/envs/ams/lib/python3.9/site-packages/andes/cases/ieee14/ieee14_ace.xlsx"...
Input file parsed in 0.4907 seconds.
Setting internal address for Bus
Setting internal address for PQ
Setting internal address for PV
Setting internal address for Slack
Setting internal address for Shunt
Setting internal address for Line
Setting internal address for Area
System internal structure set up in 0.0455 seconds.


In [5]:
ams.config_logger(stream_level=10)

In [6]:
case1 = ams.get_case('matpower/case14.m')
case2 = ams.get_case('ieee14/ieee14.xlsx')
case3 = ams.get_case('matpower/case_ACTIVSg2000.m')
sp = ams.load(case1, setup=True,)

ppc = ams.io.pypower.system2ppc(sp)

Working directory: "/Users/jinningwang/Documents/work/ams/dev/demo"
Found files: ['/Users/jinningwang/Documents/work/ams/ams/cases/matpower/case14.m']
Input format guessed as matpower.
Parsing input file "/Users/jinningwang/Documents/work/ams/ams/cases/matpower/case14.m"...
Detected raw file encoding: {'encoding': 'ascii', 'confidence': 1.0, 'language': ''}
CASE14    Power flow data for IEEE 14 bus test case.
Input file parsed in 0.0394 seconds.
Line rate_a is corrected to large value automatically.
Adjusting the bus index to start from 0.
System set up in 0.0108 seconds.
Adjusting the bus index to start from 0.


In [7]:
sp.DCOPF.run(solver='GUROBI')

Setup model of DCOPF
- Generating symbols for DCOPF
Set constrs power balance: self.constrs["pb"]=cp.sum(self.routine.pd.v) - cp.sum(self.pg) == 0
Set constrs line limits upper bound: self.constrs["lub"]=self.routine.PTDF1.v @ (self.pg - self.routine.pd1.v) - self.routine.PTDF2.v @ self.routine.pd2.v - self.routine.rate_a.v <= 0
Set constrs line limits lower bound: self.constrs["llb"]=- self.routine.PTDF1.v @ (self.pg - self.routine.pd1.v) + self.routine.PTDF2.v @ self.routine.pd2.v - self.routine.rate_a.v <= 0
DCOPF model set up in 0.0067 seconds.


Set parameter Username
Academic license - for non-commercial use only - expires 2024-05-21


DCOPF completed in 0.0152 seconds with exit code 0.


In [8]:
sp.DCOPF.obj

tc: sum(c2 * pg**2 + c1 * pg + c0), tc=7642.5918

In [9]:
sp.DCOPF.pg.v

array([2.20967695, 0.38032305, 0.        , 0.        , 0.        ])

In [10]:
sp.ACOPF.run()

Setup model for ACOPF
- Generating symbols for ACOPF
Set constrs power balance: self.constrs["pb"]=cp.sum(self.routine.pd.v) - cp.sum(self.pg) == 0
ACOPF model set up in 0.0059 seconds.
Adjusting the bus index to start from 0.
PYPOWER Version 5.1.4, 27-June-2018
 -- AC Optimal Power Flow



Python Interior Point Solver - PIPS, Version 1.0, 07-Feb-2011


ACOPF completed in 0.2401 seconds with exit code 0.


Converged!


0

In [11]:
sp.ACOPF.obj

tc: sum(c2 * pg**2 + c1 * pg + c0), tc=8186.8829

In [12]:
sp.ACOPF.pg.v

array([1.52170203, 0.40208407, 0.52814901, 0.0003197 , 0.19826406])

In [13]:
sp.ACOPF.qg.v

array([0.05073508, 0.13834569, 0.19927507, 0.09809777, 0.07063822])

In [14]:
sp.ACOPF.aBus.v

array([ 0.        , -0.05270412, -0.12676006, -0.12193981, -0.10546813,
       -0.19070688, -0.15258788, -0.1211677 , -0.18850874, -0.1939532 ,
       -0.19456553, -0.20486421, -0.20523061, -0.2135537 ])

In [15]:
sp.ACOPF.vBus.v

array([1.05999989, 1.04227009, 1.0228202 , 1.0188708 , 1.01989242,
       1.05999979, 1.04877868, 1.05999964, 1.0467066 , 1.04171286,
       1.04741529, 1.04497152, 1.04047321, 1.02585715])