#  Routines PFlow

In [1]:
import ams
import numpy as np

print(ams.__version__)

0.6.post9.dev0+g94f1297


In [2]:
ams.config_logger(stream_level=10)

In [3]:
spa = ams.load(ams.get_case('pypower/case14.py'),
               setup=True)

Input format guessed as pypower.
Parsing input file "/home/jwang175/ams/ams/cases/pypower/case14.py"...
Input file parsed in 0.0043 seconds.
System set up in 0.0019 seconds.


In [4]:
spa.PFlow.run()

PYPOWER Version 5.1.4, 27-June-2018

Newton's method power flow converged in 2 iterations.



 -- AC Power Flow (Newton)



True

In [5]:
spa.PFlow.algebs

OrderedDict([('a_Bus',
              OrderedDict([('algeb', Bus.a (14 Algebs) at 0x7f23e42ce130),
                           ('a', [0, 13])])),
             ('v_Bus',
              OrderedDict([('algeb', Bus.v (14 Algebs) at 0x7f23e42ce310),
                           ('a', [14, 27])])),
             ('q_PV',
              OrderedDict([('algeb', PV.q (4 Algebs) at 0x7f23e42d89d0),
                           ('a', [28, 31])])),
             ('p_Slack',
              OrderedDict([('algeb', Slack.p (1 Algeb) at 0x7f23e42663d0),
                           ('a', [32])])),
             ('q_Slack',
              OrderedDict([('algeb', Slack.q (1 Algeb) at 0x7f23e4266610),
                           ('a', [33])]))])

In [6]:
spa.PFlow.v

array([ 1.06000000e+00,  1.04500000e+00,  1.01000000e+00,  1.01900000e+00,
        1.02000000e+00,  1.07000000e+00,  1.06200000e+00,  1.09000000e+00,
        1.05600000e+00,  1.05100000e+00,  1.05700000e+00,  1.05500000e+00,
        1.05000000e+00,  1.03600000e+00,  0.00000000e+00, -8.69173967e-02,
       -2.22005881e-01, -1.80292512e-01, -1.53239908e-01, -2.48185820e-01,
       -2.33350521e-01, -2.33175988e-01, -2.60752190e-01, -2.63544717e-01,
       -2.58134196e-01, -2.63021118e-01, -2.64591915e-01, -2.79950812e-01,
        4.24000000e+01,  2.34000000e+01,  1.22000000e+01,  1.74000000e+01,
        2.32400000e+02, -1.69000000e+01])

In [7]:
spa.Bus.a.v

array([1.06 , 1.045, 1.01 , 1.019, 1.02 , 1.07 , 1.062, 1.09 , 1.056,
       1.051, 1.057, 1.055, 1.05 , 1.036])

In [8]:
spa.Bus.v.v

array([ 0.        , -0.0869174 , -0.22200588, -0.18029251, -0.15323991,
       -0.24818582, -0.23335052, -0.23317599, -0.26075219, -0.26354472,
       -0.2581342 , -0.26302112, -0.26459191, -0.27995081])

In [9]:
ppca = ams.io.pypower.system2ppc(spa)

In [10]:
ppc = ams.io.pypower.py2ppc(ams.get_case('pypower/case14.py'))

In [11]:
from ams.solver.pypower.runpf import runpf

In [12]:
ra, _ = runpf(ppca)

PYPOWER Version 5.1.4, 27-June-2018

Newton's method power flow converged in 2 iterations.



 -- AC Power Flow (Newton)



In [13]:
rc, _ = runpf(ppc)

PYPOWER Version 5.1.4, 27-June-2018

Newton's method power flow converged in 2 iterations.



 -- AC Power Flow (Newton)



Bus voltage

In [14]:
np.allclose(ra['bus'][:, 7], rc['bus'][:, 7], rtol=1e-05, atol=1e-08, equal_nan=False)

True

Bus angle

In [15]:
np.allclose(ra['bus'][:, 8], rc['bus'][:, 8], rtol=1e-05, atol=1e-08, equal_nan=False)

True