#  Routine Var

In [1]:
import ams
import numpy as np

print(ams.__version__)

0.6.1.post14.dev0+g32619ba


In [2]:
ams.config_logger(stream_level=10)

In [3]:
spa = ams.load(ams.get_case('pypower/case14.py'),
               setup=True)

Input format guessed as pypower.
Parsing input file "/Users/jinningwang/Documents/work/ams/ams/cases/pypower/case14.py"...
Input file parsed in 0.0038 seconds.
System set up in 0.0011 seconds.


In [4]:
spa.PFlow.ralgebs

OrderedDict([('aBus', <ams.core.var.RAlgeb at 0x146980f10>),
             ('vBus', <ams.core.var.RAlgeb at 0x146980f40>),
             ('qPV', <ams.core.var.RAlgeb at 0x146980f70>),
             ('pSlack', <ams.core.var.RAlgeb at 0x146980fa0>),
             ('qSlack', <ams.core.var.RAlgeb at 0x146980fd0>)])

In [5]:
spa.PFlow.run()

PYPOWER Version 5.1.4, 27-June-2018

Newton's method power flow converged in 2 iterations.



 -- AC Power Flow (Newton)



True

In [6]:
spa.PFlow.ralgebs['aBus'].v

array([ 0.        , -0.0869174 , -0.22200588, -0.18029251, -0.15323991,
       -0.24818582, -0.23335052, -0.23317599, -0.26075219, -0.26354472,
       -0.2581342 , -0.26302112, -0.26459191, -0.27995081])

In [7]:
spa.Bus.a.v[0] = -1

In [8]:
spa.Bus.a.v

array([-1.        , -0.0869174 , -0.22200588, -0.18029251, -0.15323991,
       -0.24818582, -0.23335052, -0.23317599, -0.26075219, -0.26354472,
       -0.2581342 , -0.26302112, -0.26459191, -0.27995081])

In [9]:
spa.PFlow.ralgebs['aBus'].v

array([ 0.        , -0.0869174 , -0.22200588, -0.18029251, -0.15323991,
       -0.24818582, -0.23335052, -0.23317599, -0.26075219, -0.26354472,
       -0.2581342 , -0.26302112, -0.26459191, -0.27995081])