#  From PyPower

In [1]:
from collections import OrderedDict

import numpy as np
import pandas as pd

import ams
import andes

print(ams.__version__)
print(andes.__version__)

0.5+175.g03d6c6e.dirty
1.8.5


In [2]:
ams.config_logger(stream_level='INFO')

In [3]:
sa = andes.load(andes.get_case('ieee14/ieee14_ace.xlsx'),
                no_output=True,
                setup=True,
                pflow=True,)

Generating code for 1 models on 8 processes.


In [4]:
sp = ams.load(ams.get_case('ieee14/ieee14.xlsx'),
            setup=True)
key, col = sp._key, sp._col

Parsing input file "/Users/jinningwang/Documents/work/ams/ams/cases/ieee14/ieee14.xlsx"...
Input file parsed in 0.0235 seconds.
System set up  and initialize in 0.0244 seconds.


In [5]:
exit_code, res = sp.PFlow.run()

PYPOWER Version 5.1.4, 27-June-2018

Newton's method power flow converged in 4 iterations.



 -- AC Power Flow (Newton)



In [6]:
sp.Bus.a.v

array([ 0.        , -0.09801016, -0.18923209, -0.18112383, -0.15897145,
       -0.2729972 , -0.24570065, -0.24511489, -0.27958403, -0.28380244,
       -0.28085048, -0.29034285, -0.29407839, -0.32139303])

In [7]:
sp.Bus.v.v

array([1.03      , 1.03      , 1.01      , 1.00167808, 1.0073932 ,
       1.03      , 1.01855747, 1.03      , 1.01818536, 1.0126388 ,
       1.01770533, 1.01707911, 1.01398707, 1.01401075])

In [8]:
sp.PV.q.v

array([69.41396739, 31.18465272, 29.29718131,  8.6705239 ])

In [9]:
sp.Slack.p.v

array([234.28905397])

In [10]:
sp.Slack.q.v

array([-50.98582412])

In [11]:
sp.PFlow.algebs['a_Bus']['algeb'].v

array([ 0.        , -0.09801016, -0.18923209, -0.18112383, -0.15897145,
       -0.2729972 , -0.24570065, -0.24511489, -0.27958403, -0.28380244,
       -0.28085048, -0.29034285, -0.29407839, -0.32139303])