# Unit Commitment

In [1]:
import numpy as np

import andes
import ams

import pandas as pd

import json

import cvxpy as cp

In [2]:
ams.__version__

'0.6.5.post94.dev0+ga02fa3b'

In [3]:
ams.config_logger(stream_level=10)

In [4]:
sp = ams.load(ams.get_case('ieee14/ieee14_rted.xlsx'),
              setup=True,
              )

Input format guessed as xlsx.
Parsing input file "/Users/jinningwang/Documents/work/ams/ams/cases/ieee14/ieee14_rted.xlsx"...
Input file parsed in 0.4025 seconds.
Adjust bus index to start from 0.
System set up in 0.0039 seconds.


In [5]:
sp.RTED.run()

Setup model of RTED
RTED data check passed.
- Generating symbols for RTED
Set constrs pb: sum(pd1) + sum(pd2) - sum(pg)
Set constrs lub: PTDF1 @ (pg - pd1) - PTDF2 * pd2 - rate_a
Set constrs llb: - PTDF1 @ (pg - pd1) + PTDF2 * pd2 - rate_a
Set constrs rbu: gs @ pru - du
Set constrs rbd: gs @ prd - dd
Set constrs rru: pg + pru - pmax
Set constrs rrd: -pg + prd - pmin
Set constrs rgu: pg - pg0 - R10
Set constrs rgd: -pg + pg0 - R10
RTED model set up in 0.0098 seconds.
RTED solved as optimal in 0.0098 seconds with exit code 0.


True

In [6]:
sp = ams.load(ams.get_case('ieee14/ieee14_uc.xlsx'),
              setup=True,
              )

Input format guessed as xlsx.
Parsing input file "/Users/jinningwang/Documents/work/ams/ams/cases/ieee14/ieee14_uc.xlsx"...
Input file parsed in 0.0409 seconds.
Adjust bus index to start from 0.
System set up in 0.0032 seconds.


In [7]:
sp.ED.run()

Setup model of ED
ED data check passed.
- Generating symbols for ED
Set constrs pb: pds - Spg @ pg
Set constrs lub: PTDF1@pg - PTDF1@pd1s - PTDF2@pd2s - RAr@cdup
Set constrs llb: -PTDF1@pg + PTDF1@pd1s + PTDF2@pd2s - RAr@cdup
Set constrs rgu: pg @ Mr - RR30
Set constrs rgd: -pg @ Mr - RR30
ED model set up in 0.0138 seconds.
ED solved as optimal in 0.0165 seconds with exit code 0.


True

In [8]:
sp.UC.setup()

UC data check passed.
- Generating symbols for UC
Set constrs actv: ugd @ Mr - vgd[:, 1:]
Set constrs actv0: ugd[:, 0] - ug0  - vgd[:, 0]
Set constrs actw: -ugd @ Mr - wgd[:, 1:]
Set constrs actw0: -ugd[:, 0] + ug0 - wgd[:, 0]
UC model set up in 0.0163 seconds.


True

In [9]:
sp.UC.run(solver='GUROBI')

Set parameter Username
Academic license - for non-commercial use only - expires 2024-05-21


UC solved as optimal in 0.0274 seconds with exit code 0.


True

In [10]:
sp.UC.ugd

Var: StaticGen.ugd, a=[5 6 7 8 9], v=[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]

In [11]:
sp.UC.vgd

Var: StaticGen.vgd, a=[10 11 12 13 14], v=[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]

In [12]:
sp.UC.wgd

Var: StaticGen.wgd, a=[15 16 17 18 19], v=[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]