# Distributional OPF

In [1]:
import numpy as np

import andes
import ams

import pandas as pd

import json

import cvxpy as cp

In [2]:
ams.__version__

'0.6.5.post111.dev0+g3952d43'

In [3]:
ams.config_logger(stream_level=10)

In [4]:
sp = ams.load(ams.get_case('ieee123/case123_v1.m'),
              setup=True,
              )

Input format guessed as matpower.
Parsing input file "/Users/jinningwang/Documents/work/ams/ams/cases/ieee123/case123_v1.m"...
Input file parsed in 0.0182 seconds.
Adjust bus index to start from 0.
System set up in 0.0081 seconds.


In [5]:
sp.LDOPF.setup()

LDOPF data check passed.
- Generating symbols for LDOPF
Set constrs pb: CftT@(pl - r * isq)- pn
Set constrs pinj: Cg@(pn - pd) - pg
Set constrs lub: isq - rate_a**2
Set constrs llb: -isq + rate_a**2
Set constrs vu: vsq - vmax**2
Set constrs vl: -vsq + vmin**2
Set constrs qinj: Cg@(qn - qd) - qg
Set constrs qb: CftT@(ql - x * isq)- qn
Set constrs lvd: Cft@vsq - (r * pl + x * ql)
LDOPF model set up in 0.0099 seconds.


True

In [6]:
sp.LDOPF.run()

LDOPF solved as optimal in 0.0549 seconds with exit code 0.


True

In [7]:
sp.LDOPF.pg.v

array([ 0.00999873,  0.00999832,  0.00092266,  0.00999882,  0.0100006 ,
        0.00999856,  0.00999915,  0.01000018, -0.00022731,  0.00011843,
        0.00999945])

In [8]:
sp.StaticGen.get(src='p', attr='v', idx=sp.StaticGen.get_idx())

array([ 0.00999873,  0.00999832,  0.00092266,  0.00999882,  0.0100006 ,
        0.00999856,  0.00999915,  0.01000018, -0.00022731,  0.00011843,
        0.00999945])

In [9]:
sp.LDOPF.qg.v

array([-0.00065413, -0.00148251, -0.10500044,  0.001092  , -0.00303728,
       -0.00109916, -0.00411546, -0.00497113, -0.00091074,  0.00167205,
        0.0050267 ])

In [10]:
sp.StaticGen.get(src='q', attr='v', idx=sp.StaticGen.get_idx())

array([-0.00065413, -0.00148251, -0.10500044,  0.001092  , -0.00303728,
       -0.00109916, -0.00411546, -0.00497113, -0.00091074,  0.00167205,
        0.0050267 ])