# Manipulate the Simulation

This example shows how to play with the simulation,
such as contingency analysis and manipulate the constraints.

In [1]:
import ams

In [2]:
ams.config_logger(stream_level=20)

## Manipulate the Simulation

### Load Case

In [3]:
sp = ams.load(ams.get_case('5bus/pjm5bus_uced.xlsx'),
              setup=True,
              no_output=True,)

Parsing input file "/Users/jinningwang/work/miniconda3/envs/amsre/lib/python3.12/site-packages/ams/cases/5bus/pjm5bus_uced.xlsx"...
Input file parsed in 0.0664 seconds.
Zero line rates detacted in rate_b, rate_c, adjusted to 999.
System set up in 0.0016 seconds.


The system load are defined in model `PQ`.

In [4]:
sp.PQ.as_df()

idx    u  name    bus     Vn   p0      q0  vmax  vmin owner  ctrl
uid                                                                    
0    PQ_1  1.0  PQ 1  Bus_2  230.0  3.0  0.9861   1.1   0.9  None   1.0
1    PQ_2  1.0  PQ 2  Bus_3  230.0  3.0  0.9861   1.1   0.9  None   1.0
2    PQ_3  1.0  PQ 3  Bus_4  230.0  4.0  1.3147   1.1   0.9  None   1.0

In RTED, system load is referred as `pd`.

In [5]:
sp.RTED.pd.v

array([3., 3., 4.])

### Run Simulation

RTED can be solved and we can inspect the results as discussed in
previous example.

In [6]:
sp.RTED.run(solver='CLARABEL')

Building system matrices
Parsing OModel for <RTED>
Evaluating OModel for <RTED>
Finalizing OModel for <RTED>
<RTED> initialized in 0.0103 seconds.
<RTED> solved as optimal in 0.0102 seconds, converged in 10 iterations with CLARABEL.


True

Power generation `pg` and line flow `plf` can be accessed as follows.

In [7]:
sp.RTED.pg.v

array([2.1, 5.2, 0.7, 2. ])

In [8]:
sp.RTED.plf.v

array([ 0.70595331,  0.68616798,  0.00192539, -1.58809337,  0.61190663,
       -0.70192539,  0.70595331])

### Change Load

The load values can be manipulated in the model `PQ`.

Note the difference between `Model.set` and `Model.alter`:

`set`: This method ***WILL NOT*** modify the input values from the case file that have not been converted to the system base. As a result, changes applied by this method ***WILL NOT*** affect the dumped case file.

`alter`: If the method operates on an input parameter, the new data ***should be in the same base as that in the input file***. This function will convert ``value`` to per unit in the system base whenever necessary. The values for storing the input data, i.e., the parameter's ``vin`` field, will be overwritten. As a result, altered values ***WILL BE*** reflected in the dumped case file.

In [9]:
sp.PQ.alter(src='p0', idx=['PQ_1', 'PQ_2'], value=[3.2, 3.2])

According parameters need to be updated to make the changes effective in the optimization model.
If not sure which parameters need to be updated, we can use
``update()`` to update all parameters.

In [10]:
sp.RTED.update('pd')

True

After manipulation, the routined can be solved again.

In [11]:
sp.RTED.run(solver='CLARABEL')

<RTED> solved as optimal in 0.0011 seconds, converged in 10 iterations with CLARABEL.


True

In [12]:
sp.RTED.pg.v

array([2.09999999, 5.19999999, 1.10000002, 2.        ])

An alternative way is to alter the load through ``RTED``.

As ``pd`` has owner ``StaticLoad`` and soruce ``p0``, the parameter update through ``RTED`` actually happens to ``StaticLoad.p0``.

In [13]:
sp.RTED.pd.owner

StaticLoad (3 devices) at 0x337b2a660

In [14]:
sp.RTED.pd.src

'p0'

Similarly, the load can be changed using ``set`` method.

In [15]:
sp.RTED.set(src='pd', attr='v', idx=['PQ_1', 'PQ_2'], value=[0.2, 0.2])

True

Remember to update the optimization parameters after the change.

In [16]:
sp.RTED.update('pd')

True

We can see that the original load is also updated.

In [17]:
sp.PQ.as_df()

idx    u  name    bus     Vn   p0      q0  vmax  vmin owner  ctrl
uid                                                                    
0    PQ_1  1.0  PQ 1  Bus_2  230.0  0.2  0.9861   1.1   0.9  None   1.0
1    PQ_2  1.0  PQ 2  Bus_3  230.0  0.2  0.9861   1.1   0.9  None   1.0
2    PQ_3  1.0  PQ 3  Bus_4  230.0  4.0  1.3147   1.1   0.9  None   1.0

In [18]:
sp.RTED.run(solver='CLARABEL')

<RTED> solved as optimal in 0.0012 seconds, converged in 10 iterations with CLARABEL.


True

As expected, the power generation also changed.

In [19]:
sp.RTED.pg.v

array([1.30000001, 0.5       , 0.6       , 1.99999999])

### Trip a Generator

We can see that there are three PV generators in the system.

> **Warning:** in `MatProcessor`, `StaticGen` online status is NOT considered in its connectivity matrix `Cg`.
> The same applies for `PQ`, `Line`, and `Shunt`.

In [20]:
sp.PV.as_df()

idx    u      name     Sn     Vn    bus  busr      p0   q0  pmax  ...  \
uid                                                                     ...   
0    PV_1  1.0      Alta  100.0  230.0  Bus_1  None  1.0000  0.0   2.1  ...   
1    PV_3  1.0  Solitude  100.0  230.0  Bus_3  None  3.2349  0.0   5.2  ...   
2    PV_5  1.0  Brighton  100.0  230.0  Bus_5  None  4.6651  0.0   6.0  ...   

     Qc2min  Qc2max   Ragc    R10    R30     Rq  apf  pg0  td1  td2  
uid                                                                  
0       0.0     0.0  999.0  999.0  999.0  999.0  0.0  0.0  0.5  0.0  
1       0.0     0.0  999.0  999.0  999.0  999.0  0.0  0.0  0.5  0.0  
2       0.0     0.0  999.0  999.0  999.0  999.0  0.0  0.0  0.5  0.0  

[3 rows x 34 columns]

`PV_1` is tripped by setting its connection status `u` to 0.

In [21]:
sp.StaticGen.set(src='u', idx='PV_1', attr='v', value=0)

True

In AMS, some parameters are defiend as constants in the numerical optimization model
to follow the CVXPY DCP and DPP rules.
Once non-parametric parameters are changed, the optimization model will be
re-initialized to make the changes effective.

More details can be found at [CVXPY - Disciplined Convex Programming](https://www.cvxpy.org/tutorial/dcp/index.html#disciplined-convex-programming).

In [22]:
sp.RTED.update()

Building system matrices
<RTED> reinit OModel due to non-parametric change.
Evaluating OModel for <RTED>
Finalizing OModel for <RTED>


True

Then we can re-solve the model.

In [23]:
sp.RTED.run(solver='CLARABEL')

<RTED> solved as optimal in 0.0098 seconds, converged in 9 iterations with CLARABEL.


True

We can see that the tripped generator has no power generation.

In [24]:
sp.RTED.pg.v.round(2)

array([-0. ,  1.8,  0.6,  2. ])

### Trip a Line

We can inspect the `Line` model to check the system topology.

In [25]:
sp.Line.as_df()

idx    u      name   bus1   bus2     Sn    fn    Vn1    Vn2        r  \
uid                                                                            
0    Line_0  1.0   Line AB  Bus_1  Bus_2  100.0  60.0  230.0  230.0  0.00281   
1    Line_1  1.0   Line AD  Bus_1  Bus_4  100.0  60.0  230.0  230.0  0.00304   
2    Line_2  1.0   Line AE  Bus_1  Bus_5  100.0  60.0  230.0  230.0  0.00064   
3    Line_3  1.0   Line BC  Bus_2  Bus_3  100.0  60.0  230.0  230.0  0.00108   
4    Line_4  1.0   Line CD  Bus_3  Bus_4  100.0  60.0  230.0  230.0  0.00297   
5    Line_5  1.0   Line DE  Bus_4  Bus_5  100.0  60.0  230.0  230.0  0.00297   
6    Line_6  1.0  Line AB2  Bus_1  Bus_2  100.0  60.0  230.0  230.0  0.00281   

     ...  tap  phi  rate_a  rate_b  rate_c  owner  xcoord  ycoord      amin  \
uid  ...                                                                      
0    ...  1.0  0.0     4.0   999.0   999.0   None    None    None -6.283185   
1    ...  1.0  0.0     2.0   999.0   999.0   None    None    None -6.283185   
2    ...  1.0  0.0     2.0   999.0   999.0   None    None    None -6.283185   
3    ...  1.0  0.0     2.0   999.0   999.0   None    None    None -6.283185   
4    ...  1.0  0.0     2.0   999.0   999.0   None    None    None -6.283185   
5    ...  1.0  0.0     2.4   999.0   999.0   None    None    None -6.283185   
6    ...  1.0  0.0     4.0   999.0   999.0   None    None    None -6.283185   

         amax  
uid            
0    6.283185  
1    6.283185  
2    6.283185  
3    6.283185  
4    6.283185  
5    6.283185  
6    6.283185  

[7 rows x 28 columns]

Here line `2` is tripped by setting its connection status `u` to 0.

Note that in ANDES, dynamic simulation of *line tripping should use model ``Toggle``.*

In [26]:
sp.Line.alter(src='u', idx='Line_1', value=0)

In [27]:
sp.RTED.update()

Building system matrices
<RTED> reinit OModel due to non-parametric change.
Evaluating OModel for <RTED>
Finalizing OModel for <RTED>


True

In [28]:
sp.RTED.run(solver='CLARABEL')

<RTED> solved as optimal in 0.0094 seconds, converged in 9 iterations with CLARABEL.


True

Here we can see the tripped line has no flow.

In [29]:
sp.RTED.plf.v.round(2)

array([-0.12,  0.  ,  0.24, -0.44,  1.16, -0.84, -0.12])

## Disable Constraints

In addition to the system parameters, the constraints can also be manipulated.

Here, we load the case to a new system.

In [30]:
spc = ams.load(ams.get_case('5bus/pjm5bus_uced.xlsx'),
               setup=True,
               no_output=True,)

Parsing input file "/Users/jinningwang/work/miniconda3/envs/amsre/lib/python3.12/site-packages/ams/cases/5bus/pjm5bus_uced.xlsx"...
Input file parsed in 0.0248 seconds.
Zero line rates detacted in rate_b, rate_c, adjusted to 999.
System set up in 0.0017 seconds.


In [31]:
spc.RTED.init()

Building system matrices
Parsing OModel for <RTED>
Evaluating OModel for <RTED>
Finalizing OModel for <RTED>
<RTED> initialized in 0.0090 seconds.


True

In [32]:
spc.RTED.set(src='rate_a', idx=['Line_3'], attr='v', value=0.6)

True

In [33]:
spc.RTED.update('rate_a')

True

We can inspect the constraints status as follows.
All constraints are turned on by default.

In [34]:
spc.RTED.constrs

OrderedDict([('pb', Constraint: pb [ON]),
             ('sba', Constraint: sbus [ON]),
             ('pglb', Constraint: pglb [ON]),
             ('pgub', Constraint: pgub [ON]),
             ('plflb', Constraint: plflb [ON]),
             ('plfub', Constraint: plfub [ON]),
             ('alflb', Constraint: alflb [ON]),
             ('alfub', Constraint: alfub [ON]),
             ('rbu', Constraint: rbu [ON]),
             ('rbd', Constraint: rbd [ON]),
             ('rru', Constraint: rru [ON]),
             ('rrd', Constraint: rrd [ON]),
             ('rgu', Constraint: rgu [ON]),
             ('rgd', Constraint: rgd [ON])])

Then, solve the dispatch and inspect the line flow.

In [35]:
spc.RTED.run(solver='CLARABEL')

<RTED> solved as optimal in 0.0332 seconds, converged in 10 iterations with CLARABEL.


True

In [36]:
spc.RTED.plf.v.round(2)

array([ 1.2 ,  0.87, -1.17, -0.6 , -0.02, -1.15,  1.2 ])

In the next, we can disable specific constraints, and the parameter name takes both single constraint name or a list of constraint names.

In [37]:
spc.RTED.disable(['plflb', 'plfub'])

Turn off constraints: plflb, plfub


True

Now, it can be seen that the two constraints are disabled.

In [38]:
spc.RTED.constrs

OrderedDict([('pb', Constraint: pb [ON]),
             ('sba', Constraint: sbus [ON]),
             ('pglb', Constraint: pglb [ON]),
             ('pgub', Constraint: pgub [ON]),
             ('plflb', Constraint: plflb [OFF]),
             ('plfub', Constraint: plfub [OFF]),
             ('alflb', Constraint: alflb [ON]),
             ('alfub', Constraint: alfub [ON]),
             ('rbu', Constraint: rbu [ON]),
             ('rbd', Constraint: rbd [ON]),
             ('rru', Constraint: rru [ON]),
             ('rrd', Constraint: rrd [ON]),
             ('rgu', Constraint: rgu [ON]),
             ('rgd', Constraint: rgd [ON])])

In [39]:
spc.RTED.run(solver='CLARABEL')

Disabled constraints: plflb, plfub
Finalizing OModel for <RTED>
<RTED> initialized in 0.0018 seconds.
<RTED> solved as optimal in 0.0082 seconds, converged in 9 iterations with CLARABEL.


True

We can see that now the line flow limits are not in effect.

In [40]:
spc.RTED.plf.v.round(2)

array([ 0.71,  0.69,  0.  , -1.59,  0.61, -0.7 ,  0.71])

Similarly, you can also enable the constraints again.

In [41]:
spc.RTED.enable(['plflb', 'plfub'])

Turn on constraints: plflb, plfub


True

In [42]:
spc.RTED.constrs

OrderedDict([('pb', Constraint: pb [ON]),
             ('sba', Constraint: sbus [ON]),
             ('pglb', Constraint: pglb [ON]),
             ('pgub', Constraint: pgub [ON]),
             ('plflb', Constraint: plflb [ON]),
             ('plfub', Constraint: plfub [ON]),
             ('alflb', Constraint: alflb [ON]),
             ('alfub', Constraint: alfub [ON]),
             ('rbu', Constraint: rbu [ON]),
             ('rbd', Constraint: rbd [ON]),
             ('rru', Constraint: rru [ON]),
             ('rrd', Constraint: rrd [ON]),
             ('rgu', Constraint: rgu [ON]),
             ('rgd', Constraint: rgd [ON])])

In [43]:
spc.RTED.run(solver='CLARABEL')

Finalizing OModel for <RTED>
<RTED> initialized in 0.0011 seconds.
<RTED> solved as optimal in 0.0087 seconds, converged in 10 iterations with CLARABEL.


True

In [44]:
spc.RTED.plf.v.round(2)

array([ 1.2 ,  0.87, -1.17, -0.6 , -0.02, -1.15,  1.2 ])

Alternatively, you can also **force init** the dispatch to rebuild the system matrices, enable all constraints, and re-init the optimization models.

In [45]:
spc.RTED.disable(['plflb', 'plfub', 'rgu', 'rgd'])

Turn off constraints: plflb, plfub, rgu, rgd


True

In [46]:
spc.RTED.init(force=True)

Disabled constraints: plflb, plfub, rgu, rgd
Finalizing OModel for <RTED>
<RTED> initialized in 0.0016 seconds.


True

In [47]:
spc.RTED.constrs

OrderedDict([('pb', Constraint: pb [ON]),
             ('sba', Constraint: sbus [ON]),
             ('pglb', Constraint: pglb [ON]),
             ('pgub', Constraint: pgub [ON]),
             ('plflb', Constraint: plflb [OFF]),
             ('plfub', Constraint: plfub [OFF]),
             ('alflb', Constraint: alflb [ON]),
             ('alfub', Constraint: alfub [ON]),
             ('rbu', Constraint: rbu [ON]),
             ('rbd', Constraint: rbd [ON]),
             ('rru', Constraint: rru [ON]),
             ('rrd', Constraint: rrd [ON]),
             ('rgu', Constraint: rgu [OFF]),
             ('rgd', Constraint: rgd [OFF])])

## Alter Config

Routines have an ``config`` attribute as configuration settings.

In [48]:
spf = ams.load(ams.get_case('5bus/pjm5bus_uced.xlsx'),
               setup=True,
               no_output=True,)

Parsing input file "/Users/jinningwang/work/miniconda3/envs/amsre/lib/python3.12/site-packages/ams/cases/5bus/pjm5bus_uced.xlsx"...
Input file parsed in 0.0254 seconds.
Zero line rates detacted in rate_b, rate_c, adjusted to 999.
System set up in 0.0016 seconds.


In RTED, the default interval is 5/60 [hour], and the formulations has been adjusted to fit the interval.

In [49]:
spf.RTED.config

OrderedDict({'t': 0.08333333333333333})

In [50]:
spf.RTED.run(solver='CLARABEL')

Building system matrices
Parsing OModel for <RTED>
Evaluating OModel for <RTED>
Finalizing OModel for <RTED>
<RTED> initialized in 0.0087 seconds.
<RTED> solved as optimal in 0.0096 seconds, converged in 10 iterations with CLARABEL.


True

In [51]:
spf.RTED.obj.v

np.float64(0.19537500002212993)

We can update the interval to 1 [hour] and re-solve the dispatch.

Note that in this senario, compared to DCOPF, RTED has extra costs for ``pru`` and ``prd``.

In [52]:
spf.RTED.config.t = 60/60

Remember to update the parameters after the change.

In [53]:
spf.RTED.update()

Building system matrices
<RTED> reinit OModel due to non-parametric change.
Evaluating OModel for <RTED>
Finalizing OModel for <RTED>


True

In [54]:
spf.RTED.run(solver='SCS')

<RTED> solved as optimal in 0.0134 seconds, converged in 325 iterations with SCS.


True

We can then get the objective value.

In [55]:
spf.RTED.obj.v

np.float64(2.344500001132924)

Note that in this build-in case, the ``cru`` and ``crd`` are defined as zero.

In [56]:
spf.RTED.cru.v

array([0., 0., 0., 0.])

In [57]:
spf.RTED.crd.v

array([0., 0., 0., 0.])

As benchmark, we can solve the DCOPF.

In [58]:
spf.DCOPF.run(solver='SCS')

Parsing OModel for <DCOPF>
Evaluating OModel for <DCOPF>
Finalizing OModel for <DCOPF>
<DCOPF> initialized in 0.0084 seconds.
<DCOPF> solved as optimal in 0.0055 seconds, converged in 225 iterations with SCS.


True

As expected, the DCOPF has a similar objective value.

In [59]:
spf.DCOPF.obj.v

np.float64(2.344500000003336)